---
- name: Nuage event callback
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
  - manageiq_connection:
      url: 'http://172.17.0.1:3000'
      username: 'admin'
      password: 'smartvm'
      manageiq_validate_certs: false
  roles:
  - xlab_si.nuage_miq_automate
  tasks:
  - debug: msg="I am a playbook running as event callback and I am able to access nuage credentials"
  - debug: var=nuage_auth
  - debug: msg="As well as details of the event that triggered me"
  - debug: var=event
  - debug: msg="So I'm now ready to do some work!"
