---
- name: Get attribute
  hosts: localhost
  connection: local
  vars:
  - manageiq_connection:
        url: 'http://172.17.0.1:3000'
        username: 'admin'
        password: 'smartvm'
        manageiq_validate_certs: false
  - object: root

  gather_facts: False
  roles:
  - syncrou.manageiq-automate
  - syncrou.manageiq-vmdb

  tasks:
    - debug: msg="Hello Automate"
    - name: "Get nuage_username as attribute"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute:
          object: "root"
          attribute: "nuage_username"
      register: result
    - debug: msg="attribute result dictionary {{ result }}"
#    - debug: msg="attribute result value is {{ result.value }}"

    - name: "Get nuage_username as state_var"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_state_var:
          attribute: "nuage_username"
      register: result
    - debug: msg="attribute result dictionary {{ result }}"
#    - debug: msg="attribute result value is {{ result.value }}"

    - name: Grab a vmdb object
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_vmdb_object:
          object: root
          attribute: event_stream
      register: result
    - debug: msg="attribute result dictionary {{ result }}"
#    - debug: msg="attribute result value is {{ result.value }}"
